### ISSUE TITLE
Pertanyaan dari Pak Rob

### ISSUE THREAD

**Issue by iqnaul** [oshdev-pdam/oshw-pdambekasi#1]
1. KiCad file sepertinya masih kurang, apakah bisa dibuatkan skema atau layout board dalam bentuk PDF saja?

2. Melihat dari kode yang dibuat, ada topology master-slave untuk metode komunikasi yang berbeda, mohon diceritakan sedikit mengenai ini

**Comment by hariantow** [comment]
1. Skematik sudah diupload dalam bentuk PDF di folder github yang sama. Sepertinya mayoritas file dapat di-convert ke format KiCad, dengan tools yang didapat dari https://github.com/thesourcerer8/altium2kicad

2. Untuk topologi master-slave, ini adalah ide pertama yang diajukan sejak Co-Creation workshop, dan sudah pernah di-deploy pada 9 November 2017. Namun di bulan Desember dilakukan redesign, dan sistem master-slave tidak lagi digunakan.
Sederhananya, master menggunakan Adafruit Feather M0 (3.3V, untuk menghemat konsumsi daya) dan slave menggunakan Arduino Micro (5V, untuk menerima data sensor [pressure transducer] yang berada di range 0.5V - 4.5V)
